### ISSUE TITLE
Add support for instrumentation of API calls

### ISSUE THREAD

**Issue by jprestel-rue** [castle/castle-python#34]
We'd like to be able to track metrics for API calls especially around timing, timeouts, and error responses. This would let us tune our timeout configuration and monitor the performance of the integration.

FWIW, a design I had in mind is the ability to register a object or function that is invoked with timing data, any exception info, and/or possibly response status code after any http request to the API. That function/object can then do with that data as it pleases.

**Comment by yuhama** [comment]
Hi! Thanks for the feedback. Although instrumentation is not something we're working on right now, it is something we'd be interested in exploring. There's some overhaul of the SDKs planned, so we'll absolutely consider putting it on the roadmap.
